# Generated by Django 4.0.6 on 2022-07-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('dailyRate', models.DecimalField(db_column='daily', decimal_places=2, max_digits=5)),
                ('birthday', models.DateField(db_column='bday')),
                ('cpf', models.CharField(db_column='cpf', max_length=11)),
                ('email', models.EmailField(db_column='email', max_length=254)),
            ],
        ),
    ]
