# Generated by Django 4.0.6 on 2022-07-13 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dailyRate',
            new_name='Valor_da_Diária',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.AddField(
            model_name='employee',
            name='Data_de_Nascimento',
            field=models.DateField(db_column='bday', default=datetime.datetime(2022, 7, 13, 18, 51, 31, 69871)),
        ),
        migrations.AddField(
            model_name='employee',
            name='Descrição_das_Atividades',
            field=models.TextField(db_column='description', default='', max_length=500),
        ),
    ]
